import type { HallLocale } from "./config";

// Explicit coverage: no English fallback for any existing hall locale.
type Story = readonly [
  headlineWork: string,
  headlineLife: string,
  proofTitle: string,
  proofBody: string,
  carryTitle: string,
  carryBody: string,
  getTitle: string,
  getBody: string,
  clockIn: string,
  clockOut: string,
  shiftExample: string,
  explore: string,
  recording: string,
  widgetsAlt: string,
  watchAlt: string,
];
const stories: Record<HallLocale, Story> = {
  en: [
    "Work ends.",
    "Your time begins.",
    "Know what's left.",
    "Set your shift. See the time remaining, your progress and today's earnings in one place.",
    "Take it with you.",
    "Home Screen widgets, Live Activities and a free Apple Watch app keep your countdown close, without opening the iPhone app every time.",
    "Make room for your time.",
    "Choose the app that fits your day. Or start with the timer in your browser.",
    "Clock in",
    "Clock out",
    "An illustrative shift",
    "Explore DoneAt",
    "Real app recording; not a live timer",
    "DoneAt countdown in the Dynamic Island, Lock Screen and Home Screen widgets",
    "DoneAt on Apple Watch showing time left, shift progress and clock-out time",
  ],
  "zh-CN": [
    "工作有终点。",
    "时间归自己。",
    "还剩多少，不必猜。",
    "设好班次，剩余时间、一天的进度和今日已赚，在一个地方看清。",
    "把时间，带离屏幕。",
    "主屏幕小组件、实时活动，还有免费的 Apple Watch App。不必每次打开 iPhone App，也能看清离下班还有多久。",
    "给自己的时间，留个位置。",
    "选一个顺手的客户端，或者先在浏览器里试试。",
    "上班",
    "下班",
    "班次示意",
    "看看 DoneAt",
    "真实 App 录屏，非实时计时器",
    "灵动岛、锁定屏幕和主屏幕小组件中的 DoneAt 倒计时",
    "Apple Watch 上的 DoneAt，显示剩余时间、班次进度和下班时刻",
  ],
  "zh-TW": [
    "工作有終點。",
    "時間歸自己。",
    "還剩多少，不必猜。",
    "設定好班次，剩餘時間、一天的進度與今日收入，在同一個地方看清。",
    "把時間，帶離螢幕。",
    "主畫面小工具、即時動態，還有免費的 Apple Watch App。不必每次打開 iPhone App，也能看清離下班還有多久。",
    "給自己的時間，留個位置。",
    "選一個順手的 App，或先在瀏覽器裡試試。",
    "上班",
    "下班",
    "班次示意",
    "看看 DoneAt",
    "真實 App 錄影，非即時計時器",
    "動態島、鎖定畫面和主畫面小工具中的 DoneAt 倒數",
    "Apple Watch 上的 DoneAt，顯示剩餘時間、班次進度和下班時刻",
  ],
  "zh-HK": [
    "工作有終點。",
    "時間歸自己。",
    "仲有幾耐，唔使估。",
    "設定好更次，剩餘時間、一天的進度與今日收入，在同一個地方看清。",
    "把時間，帶離螢幕。",
    "主畫面小工具、即時動態，還有免費的 Apple Watch App。唔使每次打開 iPhone App，都睇到仲有幾耐放工。",
    "為自己的時間，留個位置。",
    "揀一個順手的 App，或者先喺瀏覽器試吓。",
    "返工",
    "放工",
    "更次示意",
    "睇吓 DoneAt",
    "真實 App 錄影，非即時計時器",
    "動態島、鎖定畫面和主畫面小工具中的 DoneAt 倒數",
    "Apple Watch 上的 DoneAt，顯示剩餘時間、更次進度和放工時刻",
  ],
  ja: [
    "仕事が終わる。",
    "自分の時間が始まる。",
    "あとどれくらい？",
    "シフトを設定すれば、残り時間、進み具合、今日の収入をひとつの画面で確認できます。",
    "時間を、手元に。",
    "ホーム画面ウィジェット、ライブアクティビティ、無料の Apple Watch アプリ。毎回 iPhone アプリを開かずに退勤までの時間を確認できます。",
    "自分の時間に、居場所を。",
    "使いやすいアプリを選ぶか、まずはブラウザで試してみてください。",
    "出勤",
    "退勤",
    "シフトの例",
    "DoneAt を見る",
    "実際のアプリの録画です。ライブのタイマーではありません",
    "Dynamic Island、ロック画面、ホーム画面ウィジェットに表示された DoneAt のカウントダウン",
    "残り時間、シフトの進み具合、退勤時刻を表示する Apple Watch の DoneAt",
  ],
  ko: [
    "일이 끝나면,",
    "내 시간이 시작돼요.",
    "남은 시간을 한눈에.",
    "근무 시간을 설정하고 남은 시간, 진행률, 오늘의 수입을 한곳에서 확인하세요.",
    "어디서든 가까이.",
    "홈 화면 위젯, 라이브 액티비티, 무료 Apple Watch 앱으로 iPhone 앱을 매번 열지 않아도 퇴근까지 남은 시간을 볼 수 있어요.",
    "내 시간을 위한 자리.",
    "하루에 맞는 앱을 고르거나 브라우저에서 먼저 사용해 보세요.",
    "출근",
    "퇴근",
    "근무 시간 예시",
    "DoneAt 둘러보기",
    "실제 앱 녹화이며 실시간 타이머가 아닙니다",
    "Dynamic Island, 잠금 화면, 홈 화면 위젯에 표시된 DoneAt 카운트다운",
    "남은 시간, 근무 진행률, 퇴근 시간을 보여 주는 Apple Watch의 DoneAt",
  ],
  fr: [
    "Le travail s'arrête.",
    "Votre temps commence.",
    "Le temps restant, en clair.",
    "Réglez votre service. Retrouvez le temps restant, votre progression et vos gains du jour au même endroit.",
    "Gardez-le à portée de main.",
    "Widgets, activités en direct et app Apple Watch gratuite : suivez le compte à rebours sans ouvrir l'app iPhone à chaque fois.",
    "Faites place à votre temps.",
    "Choisissez l'app qui vous convient, ou essayez d'abord le minuteur dans votre navigateur.",
    "Début",
    "Fin",
    "Exemple de service",
    "Découvrir DoneAt",
    "Enregistrement réel de l'app, pas un minuteur en direct",
    "Le compte à rebours DoneAt dans la Dynamic Island et les widgets de l'écran verrouillé et de l'écran d'accueil",
    "DoneAt sur Apple Watch avec le temps restant, la progression et l'heure de fin du service",
  ],
  de: [
    "Die Arbeit endet.",
    "Deine Zeit beginnt.",
    "Wissen, was noch bleibt.",
    "Stell deine Schicht ein. Restzeit, Fortschritt und dein heutiger Verdienst stehen an einem Ort.",
    "Nimm die Zeit mit.",
    "Widgets, Live-Aktivitäten und eine kostenlose Apple Watch App zeigen den Countdown, ohne die iPhone App jedes Mal zu öffnen.",
    "Platz für deine Zeit.",
    "Wähle die passende App oder probiere zuerst den Timer im Browser aus.",
    "Arbeitsbeginn",
    "Feierabend",
    "Beispielschicht",
    "DoneAt entdecken",
    "Echte App-Aufnahme, kein Live-Timer",
    "Der DoneAt Countdown in der Dynamic Island sowie in Sperrbildschirm- und Home-Bildschirm-Widgets",
    "DoneAt auf der Apple Watch mit Restzeit, Schichtfortschritt und Feierabendzeit",
  ],
  es: [
    "El trabajo termina.",
    "Tu tiempo comienza.",
    "Sabe cuánto queda.",
    "Configura tu turno. Mira el tiempo restante, el progreso y lo ganado hoy en un solo lugar.",
    "Llévalo contigo.",
    "Widgets, actividades en directo y una app gratuita de Apple Watch muestran la cuenta atrás sin abrir siempre la app del iPhone.",
    "Haz sitio a tu tiempo.",
    "Elige la app que encaje en tu día o prueba primero el temporizador en el navegador.",
    "Entrada",
    "Salida",
    "Turno de ejemplo",
    "Explorar DoneAt",
    "Grabación real de la app; no es un temporizador en directo",
    "La cuenta atrás de DoneAt en la Dynamic Island y en los widgets de la pantalla bloqueada y de inicio",
    "DoneAt en Apple Watch con el tiempo restante, el progreso del turno y la hora de salida",
  ],
  it: [
    "Il lavoro finisce.",
    "Il tuo tempo comincia.",
    "Sai quanto manca.",
    "Imposta il turno. Tempo rimasto, avanzamento e guadagni di oggi, tutti nello stesso posto.",
    "Portalo con te.",
    "Widget, attività in tempo reale e un'app Apple Watch gratuita mostrano il conto alla rovescia senza aprire ogni volta l'app iPhone.",
    "Fai spazio al tuo tempo.",
    "Scegli l'app per la tua giornata o prova prima il timer nel browser.",
    "Inizio",
    "Fine",
    "Turno di esempio",
    "Scopri DoneAt",
    "Registrazione reale dell'app, non un timer dal vivo",
    "Il conto alla rovescia DoneAt nella Dynamic Island e nei widget della schermata di blocco e Home",
    "DoneAt su Apple Watch con tempo rimasto, avanzamento del turno e orario di uscita",
  ],
  pt: [
    "O trabalho termina.",
    "Seu tempo começa.",
    "Saiba quanto falta.",
    "Defina seu turno. Veja o tempo restante, o progresso e os ganhos de hoje em um só lugar.",
    "Leve com você.",
    "Widgets, Atividades ao Vivo e um app gratuito para Apple Watch mostram a contagem sem abrir o app do iPhone toda vez.",
    "Abra espaço para seu tempo.",
    "Escolha o app que combina com seu dia ou experimente o timer no navegador.",
    "Entrada",
    "Saída",
    "Turno de exemplo",
    "Conhecer o DoneAt",
    "Gravação real do app; não é um timer ao vivo",
    "Contagem regressiva do DoneAt na Dynamic Island e nos widgets das telas de bloqueio e de início",
    "DoneAt no Apple Watch com tempo restante, progresso do turno e horário de saída",
  ],
  ru: [
    "Работа заканчивается.",
    "Твоё время начинается.",
    "Знай, сколько осталось.",
    "Задай свою смену. Оставшееся время, прогресс и заработок за сегодня — в одном месте.",
    "Пусть время будет рядом.",
    "Виджеты, Live Activities и бесплатное приложение Apple Watch показывают обратный отсчёт без постоянного открытия приложения iPhone.",
    "Место для твоего времени.",
    "Выбери удобное приложение или сначала попробуй таймер в браузере.",
    "Начало",
    "Конец",
    "Пример смены",
    "Открыть DoneAt",
    "Запись настоящего приложения, не таймер в реальном времени",
    "Обратный отсчёт DoneAt в Dynamic Island и виджетах экрана блокировки и главного экрана",
    "DoneAt на Apple Watch: оставшееся время, прогресс смены и время окончания работы",
  ],
  "hi-IN": [
    "काम खत्म होता है।",
    "आपका समय शुरू होता है।",
    "जानें कितना समय बचा है।",
    "अपनी शिफ्ट तय करें। बचा हुआ समय, प्रगति और आज की कमाई एक ही जगह देखें।",
    "समय को पास रखें।",
    "होम स्क्रीन विजेट, लाइव ऐक्टिविटी और मुफ़्त Apple Watch ऐप से हर बार iPhone ऐप खोले बिना उलटी गिनती देखें।",
    "अपने समय के लिए जगह बनाएँ।",
    "अपने दिन के हिसाब से ऐप चुनें या पहले ब्राउज़र में टाइमर आज़माएँ।",
    "काम शुरू",
    "काम खत्म",
    "शिफ्ट का उदाहरण",
    "DoneAt देखें",
    "असली ऐप की रिकॉर्डिंग; लाइव टाइमर नहीं",
    "Dynamic Island, लॉक स्क्रीन और होम स्क्रीन विजेट में DoneAt की उलटी गिनती",
    "Apple Watch पर DoneAt में बचा हुआ समय, शिफ्ट की प्रगति और काम खत्म होने का समय",
  ],
  "mr-IN": [
    "काम संपतं.",
    "तुमचा वेळ सुरू होतो.",
    "किती वेळ उरला ते जाणून घ्या.",
    "तुमची शिफ्ट ठरवा. उरलेला वेळ, प्रगती आणि आजची कमाई एकाच ठिकाणी पाहा.",
    "वेळ जवळ ठेवा.",
    "होम स्क्रीन विजेट, लाइव्ह ॲक्टिव्हिटी आणि मोफत Apple Watch ॲपमधून प्रत्येक वेळी iPhone ॲप न उघडता उलट मोजणी पाहा.",
    "तुमच्या वेळेसाठी जागा ठेवा.",
    "दिवसाला साजेसं ॲप निवडा किंवा आधी ब्राउझरमध्ये टाइमर वापरून पाहा.",
    "काम सुरू",
    "काम संपलं",
    "शिफ्टचं उदाहरण",
    "DoneAt पाहा",
    "खऱ्या ॲपचं रेकॉर्डिंग; थेट टाइमर नाही",
    "Dynamic Island, लॉक स्क्रीन आणि होम स्क्रीन विजेटमधील DoneAt ची उलट मोजणी",
    "Apple Watch वरील DoneAt मध्ये उरलेला वेळ, शिफ्टची प्रगती आणि काम संपण्याची वेळ",
  ],
  tr: [
    "Mesai biter.",
    "Senin zamanın başlar.",
    "Ne kadar kaldığını bil.",
    "Vardiyanı ayarla. Kalan süreyi, ilerlemeyi ve bugünkü kazancını tek yerde gör.",
    "Zamanın yanında olsun.",
    "Ana ekran araç takımları, Canlı Etkinlikler ve ücretsiz Apple Watch uygulaması ile iPhone uygulamasını her seferinde açmadan geri sayımı gör.",
    "Kendi zamanına yer aç.",
    "Gününe uygun uygulamayı seç veya önce tarayıcıdaki sayacı dene.",
    "Mesai başı",
    "Mesai sonu",
    "Örnek vardiya",
    "DoneAt'i keşfet",
    "Gerçek uygulama kaydı; canlı sayaç değil",
    "Dynamic Island, kilit ekranı ve ana ekran araç takımlarında DoneAt geri sayımı",
    "Apple Watch'ta kalan süreyi, vardiya ilerlemesini ve mesai bitişini gösteren DoneAt",
  ],
  ar: [
    "للعمل نهاية.",
    "ووقتك يبدأ.",
    "اعرف كم بقي.",
    "اضبط دوامك. شاهد الوقت المتبقي والتقدم وأرباح اليوم في مكان واحد.",
    "اجعل وقتك قريبًا.",
    "أدوات الشاشة الرئيسية والأنشطة المباشرة وتطبيق Apple Watch المجاني تعرض العد التنازلي دون فتح تطبيق iPhone في كل مرة.",
    "اترك مساحة لوقتك.",
    "اختر التطبيق المناسب ليومك، أو جرّب المؤقت في المتصفح أولًا.",
    "بداية الدوام",
    "نهاية الدوام",
    "مثال لدوام",
    "اكتشف DoneAt",
    "تسجيل حقيقي للتطبيق، وليس مؤقتًا مباشرًا",
    "العد التنازلي في DoneAt ضمن Dynamic Island وأدوات شاشة القفل والشاشة الرئيسية",
    "DoneAt على Apple Watch يعرض الوقت المتبقي وتقدم الدوام ووقت نهايته",
  ],
  th: [
    "งานมีจุดสิ้นสุด",
    "เวลาของคุณเริ่มต้น",
    "รู้ว่าเหลืออีกเท่าไร",
    "ตั้งเวลางาน ดูเวลาที่เหลือ ความคืบหน้า และรายได้วันนี้ได้ในที่เดียว",
    "ให้เวลาอยู่ใกล้ตัว",
    "วิดเจ็ตหน้าจอโฮม กิจกรรมสด และแอป Apple Watch ฟรี ช่วยให้ดูเวลาที่เหลือได้โดยไม่ต้องเปิดแอป iPhone ทุกครั้ง",
    "เว้นที่ให้เวลาของคุณ",
    "เลือกแอปที่เข้ากับวันของคุณ หรือลองตัวจับเวลาในเบราว์เซอร์ก่อน",
    "เข้างาน",
    "เลิกงาน",
    "ตัวอย่างเวลางาน",
    "ดู DoneAt",
    "วิดีโอจากแอปจริง ไม่ใช่ตัวจับเวลาแบบสด",
    "เวลานับถอยหลังของ DoneAt ใน Dynamic Island และวิดเจ็ตหน้าจอล็อกกับหน้าจอโฮม",
    "DoneAt บน Apple Watch แสดงเวลาที่เหลือ ความคืบหน้าของงาน และเวลาเลิกงาน",
  ],
  id: [
    "Kerja selesai.",
    "Waktumu dimulai.",
    "Tahu berapa yang tersisa.",
    "Atur sifmu. Lihat waktu tersisa, progres, dan penghasilan hari ini di satu tempat.",
    "Bawa waktumu bersamamu.",
    "Widget, Aktivitas Langsung, dan app Apple Watch gratis menampilkan hitung mundur tanpa selalu membuka app iPhone.",
    "Beri ruang untuk waktumu.",
    "Pilih app yang cocok untuk harimu, atau coba dulu timer di browser.",
    "Mulai kerja",
    "Selesai kerja",
    "Contoh sif",
    "Jelajahi DoneAt",
    "Rekaman app asli, bukan timer langsung",
    "Hitung mundur DoneAt di Dynamic Island serta widget layar kunci dan layar utama",
    "DoneAt di Apple Watch menampilkan waktu tersisa, progres sif, dan waktu selesai kerja",
  ],
  vi: [
    "Công việc kết thúc.",
    "Thời gian của bạn bắt đầu.",
    "Biết còn bao lâu.",
    "Đặt ca làm. Xem thời gian còn lại, tiến độ và thu nhập hôm nay ở cùng một nơi.",
    "Mang thời gian theo bạn.",
    "Tiện ích, Hoạt động trực tiếp và ứng dụng Apple Watch miễn phí giúp xem đếm ngược mà không cần mở ứng dụng iPhone mỗi lần.",
    "Dành chỗ cho thời gian của bạn.",
    "Chọn ứng dụng phù hợp với ngày của bạn, hoặc thử bộ đếm trong trình duyệt trước.",
    "Bắt đầu ca",
    "Tan ca",
    "Ca làm minh họa",
    "Khám phá DoneAt",
    "Bản ghi ứng dụng thật, không phải bộ đếm trực tiếp",
    "Đếm ngược DoneAt trong Dynamic Island và tiện ích màn hình khóa, màn hình chính",
    "DoneAt trên Apple Watch hiển thị thời gian còn lại, tiến độ ca làm và giờ tan ca",
  ],
};

export function homeStory(locale: HallLocale) {
  const [
    headlineWork,
    headlineLife,
    proofTitle,
    proofBody,
    carryTitle,
    carryBody,
    getTitle,
    getBody,
    clockIn,
    clockOut,
    shiftExample,
    explore,
    recording,
    widgetsAlt,
    watchAlt,
  ] = stories[locale];
  return {
    headlineWork,
    headlineLife,
    proofTitle,
    proofBody,
    carryTitle,
    carryBody,
    getTitle,
    getBody,
    clockIn,
    clockOut,
    shiftExample,
    explore,
    recording,
    widgetsAlt,
    watchAlt,
  };
}
