import type { HallLocale } from "./config";

// Card copy. The first nine strings are copied verbatim from the product web
// app (`Off-Work-Countdown/public/locales/*/translation.json`) so the card reads
// exactly like the timer it previews; keep them in sync when the product changes.
// The last three are site-only.
export interface LiveCardCopy {
  timeLeft: string; offWorkTime: string; offWorkToday: string; restDay: string;
  nextShiftIn: string; nextShiftLabelShort: string; useOwn: string;
  startTime: string; endTime: string;
  sample: string; preview: string; backToNow: string;
}

const copy: Record<HallLocale, LiveCardCopy> = {
  "en": {
    timeLeft: "{{hours}} h {{minutes}} m {{seconds}} s",
    offWorkTime: "Off work time!",
    offWorkToday: "Done for today",
    restDay: "Not a workday today",
    nextShiftIn: "Next shift in {{time}}",
    nextShiftLabelShort: "Next shift in",
    useOwn: "Use my own hours",
    startTime: "Clock-in",
    endTime: "Clock-off",
    sample: "Sample shift · your device's clock",
    preview: "Preview clock-off",
    backToNow: "Back to now",
  },
  "zh-CN": {
    timeLeft: "{{hours}} 小时 {{minutes}} 分钟 {{seconds}} 秒",
    offWorkTime: "下班时间到！",
    offWorkToday: "今日已下班",
    restDay: "今天不上班",
    nextShiftIn: "距下次上班 {{time}}",
    nextShiftLabelShort: "距上班还有",
    useOwn: "换成我的时间",
    startTime: "上班时间",
    endTime: "下班时间",
    sample: "示例班次 · 按这台设备的时间",
    preview: "预览下班",
    backToNow: "回到现在",
  },
  "zh-TW": {
    timeLeft: "{{hours}} 小時 {{minutes}} 分鐘 {{seconds}} 秒",
    offWorkTime: "下班時間到！",
    offWorkToday: "今日已下班",
    restDay: "今天不上班",
    nextShiftIn: "距下次上班 {{time}}",
    nextShiftLabelShort: "距上班還有",
    useOwn: "換成我的時間",
    startTime: "上班時間",
    endTime: "下班時間",
    sample: "示例班次 · 依這台裝置的時間",
    preview: "預覽下班",
    backToNow: "回到現在",
  },
  "zh-HK": {
    timeLeft: "{{hours}} 小時 {{minutes}} 分 {{seconds}} 秒",
    offWorkTime: "放工時間到！",
    offWorkToday: "今日已收工",
    restDay: "今日唔使返工",
    nextShiftIn: "距下次返工 {{time}}",
    nextShiftLabelShort: "距返工仲有",
    useOwn: "換成我嘅時間",
    startTime: "返工時間",
    endTime: "放工時間",
    sample: "示例班次 · 跟這部裝置的時間",
    preview: "預覽放工",
    backToNow: "返回現在",
  },
  "ja": {
    timeLeft: "{{hours}} 時間 {{minutes}} 分 {{seconds}} 秒",
    offWorkTime: "退勤時間！",
    offWorkToday: "本日は終業",
    restDay: "今日は勤務日ではありません",
    nextShiftIn: "次の勤務まで {{time}}",
    nextShiftLabelShort: "次の勤務まで",
    useOwn: "自分の時間に変える",
    startTime: "出勤時間",
    endTime: "退勤時間",
    sample: "サンプルの勤務 · この端末の時刻",
    preview: "退勤をプレビュー",
    backToNow: "現在に戻る",
  },
  "ko": {
    timeLeft: "{{hours}} 시간 {{minutes}} 분 {{seconds}} 초",
    offWorkTime: "퇴근 시간!",
    offWorkToday: "오늘 퇴근 완료",
    restDay: "오늘은 근무일이 아닙니다",
    nextShiftIn: "다음 근무까지 {{time}}",
    nextShiftLabelShort: "다음 근무까지",
    useOwn: "내 시간으로 바꾸기",
    startTime: "출근 시간",
    endTime: "퇴근 시간",
    sample: "예시 근무 · 이 기기의 시간 기준",
    preview: "퇴근 미리 보기",
    backToNow: "지금으로 돌아가기",
  },
  "fr": {
    timeLeft: "{{hours}} h {{minutes}} m {{seconds}} s",
    offWorkTime: "C'est l'heure de la fin du travail!",
    offWorkToday: "Journée terminée",
    restDay: "Pas de travail aujourd'hui",
    nextShiftIn: "Prochain service dans {{time}}",
    nextShiftLabelShort: "Prochain service dans",
    useOwn: "Utiliser mes horaires",
    startTime: "Heure d’arrivée",
    endTime: "Heure de départ",
    sample: "Horaire d’exemple · heure de cet appareil",
    preview: "Aperçu de la sortie",
    backToNow: "Revenir à maintenant",
  },
  "de": {
    timeLeft: "{{hours}} h {{minutes}} m {{seconds}} s",
    offWorkTime: "Feierabend!",
    offWorkToday: "Feierabend für heute",
    restDay: "Heute ist kein Arbeitstag",
    nextShiftIn: "Nächste Schicht in {{time}}",
    nextShiftLabelShort: "Nächste Schicht in",
    useOwn: "Meine Zeiten verwenden",
    startTime: "Arbeitsbeginn",
    endTime: "Feierabend",
    sample: "Beispielschicht · Uhrzeit dieses Geräts",
    preview: "Feierabend ansehen",
    backToNow: "Zurück zu jetzt",
  },
  "es": {
    timeLeft: "{{hours}} h {{minutes}} m {{seconds}} s",
    offWorkTime: "¡Hora de salir del trabajo!",
    offWorkToday: "Jornada terminada",
    restDay: "Hoy no se trabaja",
    nextShiftIn: "Próximo turno en {{time}}",
    nextShiftLabelShort: "Próximo turno en",
    useOwn: "Usar mi horario",
    startTime: "Hora de entrada",
    endTime: "Hora de salida",
    sample: "Turno de ejemplo · hora de este dispositivo",
    preview: "Ver la salida",
    backToNow: "Volver a ahora",
  },
  "it": {
    timeLeft: "{{hours}} h {{minutes}} m {{seconds}} s",
    offWorkTime: "È ora di uscire dal lavoro!",
    offWorkToday: "Giornata finita",
    restDay: "Oggi non si lavora",
    nextShiftIn: "Prossimo turno tra {{time}}",
    nextShiftLabelShort: "Prossimo turno tra",
    useOwn: "Usa i miei orari",
    startTime: "Ora di ingresso",
    endTime: "Ora di uscita",
    sample: "Turno di esempio · ora di questo dispositivo",
    preview: "Anteprima dell’uscita",
    backToNow: "Torna a ora",
  },
  "pt": {
    timeLeft: "{{hours}} h {{minutes}} m {{seconds}} s",
    offWorkTime: "Hora de sair do trabalho!",
    offWorkToday: "Expediente encerrado",
    restDay: "Hoje não é dia de trabalho",
    nextShiftIn: "Próximo turno em {{time}}",
    nextShiftLabelShort: "Próximo turno em",
    useOwn: "Usar o meu horário",
    startTime: "Hora de entrada",
    endTime: "Hora de saída",
    sample: "Turno de exemplo · hora deste dispositivo",
    preview: "Ver a saída",
    backToNow: "Voltar para agora",
  },
  "ru": {
    timeLeft: "{{hours}} ч {{minutes}} м {{seconds}} с",
    offWorkTime: "Время окончания работы!",
    offWorkToday: "На сегодня всё",
    restDay: "Сегодня не рабочий день",
    nextShiftIn: "До следующей смены {{time}}",
    nextShiftLabelShort: "До смены",
    useOwn: "Указать своё время",
    startTime: "Начало работы",
    endTime: "Конец работы",
    sample: "Пример смены · время этого устройства",
    preview: "Показать конец смены",
    backToNow: "Вернуться к текущему",
  },
  "hi-IN": {
    timeLeft: "{{hours}} घंटे {{minutes}} मिनट {{seconds}} सेकंड",
    offWorkTime: "काम से छुट्टी का समय!",
    offWorkToday: "आज का काम पूरा",
    restDay: "आज कार्यदिवस नहीं है",
    nextShiftIn: "अगली शिफ़्ट {{time}} में",
    nextShiftLabelShort: "अगली शिफ़्ट में",
    useOwn: "मेरा समय इस्तेमाल करें",
    startTime: "काम शुरू",
    endTime: "छुट्टी का समय",
    sample: "उदाहरण शिफ़्ट · इस डिवाइस का समय",
    preview: "छुट्टी का पल देखें",
    backToNow: "अभी पर लौटें",
  },
  "mr-IN": {
    timeLeft: "{{hours}} तास {{minutes}} मिनिटे {{seconds}} सेकंद",
    offWorkTime: "कामावरून सुटण्याची वेळ झाली!",
    offWorkToday: "आजचे काम संपले",
    restDay: "आज कामाचा दिवस नाही",
    nextShiftIn: "पुढील शिफ्ट {{time}} मध्ये",
    nextShiftLabelShort: "पुढील शिफ्टला",
    useOwn: "माझी वेळ वापरा",
    startTime: "कामाची सुरुवात",
    endTime: "सुट्टीची वेळ",
    sample: "उदाहरण शिफ्ट · या डिव्हाइसची वेळ",
    preview: "सुटण्याची वेळ पाहा",
    backToNow: "आत्तावर परत या",
  },
  "tr": {
    timeLeft: "{{hours}} s {{minutes}} d {{seconds}} sn",
    offWorkTime: "İş çıkışı zamanı!",
    offWorkToday: "Bugünlük bitti",
    restDay: "Bugün çalışma günü değil",
    nextShiftIn: "Sonraki vardiyaya {{time}}",
    nextShiftLabelShort: "Sonraki vardiyaya",
    useOwn: "Kendi saatlerimi kullan",
    startTime: "İşe giriş",
    endTime: "İş çıkışı",
    sample: "Örnek vardiya · bu cihazın saati",
    preview: "Çıkışı önizle",
    backToNow: "Şimdiye dön",
  },
  "ar": {
    timeLeft: "{{hours}} س {{minutes}} د {{seconds}} ث",
    offWorkTime: "وقت نهاية العمل!",
    offWorkToday: "انتهى دوام اليوم",
    restDay: "اليوم ليس يوم عمل",
    nextShiftIn: "الوردية التالية بعد {{time}}",
    nextShiftLabelShort: "الوردية التالية بعد",
    useOwn: "استخدم أوقاتي",
    startTime: "وقت الحضور",
    endTime: "وقت الانصراف",
    sample: "وردية مثال · بتوقيت هذا الجهاز",
    preview: "معاينة نهاية الدوام",
    backToNow: "العودة إلى الآن",
  },
  "th": {
    timeLeft: "{{hours}} ชม {{minutes}} นาที {{seconds}} วินาที",
    offWorkTime: "ถึงเวลาออกจากงาน!",
    offWorkToday: "เลิกงานแล้ววันนี้",
    restDay: "วันนี้ไม่ใช่วันทำงาน",
    nextShiftIn: "กะถัดไปในอีก {{time}}",
    nextShiftLabelShort: "อีกกี่ชั่วโมงเข้างาน",
    useOwn: "ใช้เวลาของฉัน",
    startTime: "เวลาเข้างาน",
    endTime: "เวลาเลิกงาน",
    sample: "กะตัวอย่าง · ตามเวลาของอุปกรณ์นี้",
    preview: "ดูตอนเลิกงาน",
    backToNow: "กลับสู่ตอนนี้",
  },
  "id": {
    timeLeft: "{{hours}} jam {{minutes}} menit {{seconds}} detik",
    offWorkTime: "Waktu pulang kerja!",
    offWorkToday: "Selesai untuk hari ini",
    restDay: "Hari ini bukan hari kerja",
    nextShiftIn: "Sif berikutnya dalam {{time}}",
    nextShiftLabelShort: "Sif berikutnya dalam",
    useOwn: "Pakai jam saya",
    startTime: "Jam masuk",
    endTime: "Jam pulang",
    sample: "Contoh sif · jam perangkat ini",
    preview: "Pratinjau jam pulang",
    backToNow: "Kembali ke sekarang",
  },
  "vi": {
    timeLeft: "{{hours}} giờ {{minutes}} phút {{seconds}} giây",
    offWorkTime: "Giờ tan ca!",
    offWorkToday: "Xong việc hôm nay",
    restDay: "Hôm nay không phải ngày làm việc",
    nextShiftIn: "Ca tiếp theo sau {{time}}",
    nextShiftLabelShort: "Ca tiếp theo sau",
    useOwn: "Dùng giờ của tôi",
    startTime: "Giờ vào ca",
    endTime: "Giờ tan ca",
    sample: "Ca mẫu · theo giờ thiết bị này",
    preview: "Xem trước giờ tan ca",
    backToNow: "Quay lại hiện tại",
  },
};

export function liveCardCopy(locale: HallLocale): LiveCardCopy {
  return copy[locale];
}
